
name: piku
on: [ push, workflow_dispatch ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  PIKU_APP_NAME: hktg
  HOST_NAME: raspberrypi

jobs:
  deploy:
    name: ${{ github.workflow }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: deploy
        working-directory: ${{ github.workspace }}
        run: piku/deploy.sh 
