
name: piku
on: [ push, workflow_dispatch ]

env:
  PIKU_APP_NAME: hktg
  HOST_NAME: hellstorage

jobs:
  deploy:
    name: ${{ github.workflow }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: piku-deploy
        working-directory: ${{ github.workspace }}
        run: piku/deploy.sh ${{ env.PIKU_APP_NAME }} ${{ env.HOST_NAME }}
