
name: piku
on: [ push, workflow_dispatch ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  PIKU_APP_NAME: hktg
  HOST_NAME: raspberrypi

jobs:
  deploy:
    name: ${{ github.workflow }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Prerequisites (git remote)
        working-directory: ${{ github.workspace }}
        run: |
          app_name=$([ "${extract_branch}" == "master" ] && echo ${{ env.PIKU_APP_NAME }} || echo ${{ env.PIKU_APP_NAME }}-test)

          git remote add piku piku@${{ env.HOST_NAME }}:${app_name} ||
          git remote set-url piku piku@${{ env.HOST_NAME }}:${app_name} && 
          echo Updated piku: piku@${{ env.HOST_NAME }}:${app_name}

      - name: Deploy
        working-directory: ${{ github.workspace }}
        run: piku deploy
