
name: piku
on: [ push, workflow_dispatch ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  APPLICATION_NAME: hktg
  HOST_NAME: raspberrypi

jobs:
  deploy:
    name: ${{ github.workflow }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Prerequisites (git remote)
        working-directory: ${{ github.workspace }}
        run: |
          echo USER=${USER}
          piku
          git remote add piku piku@${{ env.HOST_NAME }}:${{ env.APPLICATION_NAME }} ||
          git remote set-url piku piku@${{ env.HOST_NAME }}:${{ env.APPLICATION_NAME }} && 
          echo Updated piku: piku@${{ env.HOST_NAME }}:${{ env.APPLICATION_NAME }}

      - name: Deploy
        working-directory: ${{ github.workspace }}
        run: piku deploy
