
name: piku
on: 
  push:
    branches:
      - master
  workflow_dispatch:

env:
  PIKU_APP_NAME: hktg

jobs:
  deploy:
    name: ${{ github.workflow }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: deploy
        working-directory: ${{ github.workspace }}
        run: piku/deploy.sh ${{ env.PIKU_APP_NAME }}
