
name: piku
on: [ push, workflow_dispatch ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  APPLICATION_NAME: hktg
  HOST_NAME: raspberrypi

jobs:
  deploy:
    name: ${{ github.workflow }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Prerequisites (git remote)
        run: |
          echo USER=${USER}
          if git ls-remote --exit-code piku; then
            git remote add piku piku@${{ env.HOST_NAME }}:${{ env.APPLICATION_NAME }}``
          else
            git remote set-url piku piku@${{ env.HOST_NAME }}:${{ env.APPLICATION_NAME }}``
          fi

      - name: Deploy
        run: git push piku master
