
name: psdpp
on: [ push, workflow_dispatch ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  APPLICATION_NAME: hktg
  HOST_NAME: raspberrypi

jobs:
  build:
    name: ${{ github.workflow }}
    runs-on: self-hosted
    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}

      - uses: actions/checkout@v3

      - name: Prerequisites
        run: git remote add piku piku@${{ env.HOST_NAME }}:${{ env.APPLICATION_NAME }}

      - name: Deploy
        run: git push piku
